### ISSUE TITLE
miss some files

### ISSUE THREAD

**Issue by zhouxincheng** [vijaydwivedi75/Beyond_word2vec#1]
could you please upload the missing files such as "STS.input.track5.en-en.txt" or give the link to it, thank you very much

**Comment by vijaydwivedi75** [comment]
Hi @zhouxincheng , the file you mention was for a Similarity Task. The file had pairs of sentences for testing the performance of the model.

If you would want to try the model implementation, please skip that part by

- You can comment [line #73](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/siamese_lstm.py#L73) in the file [siamese_lstm.py](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/siamese_lstm.py) (Btw, I just changed that in a new commit).

- You can comment lines #33, #45-50, #272-275 in the file [preprocess_data_lstm.py](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/preprocess_data_lstm.py) 

Apologies for the trouble during your implementation. This work was on a very 'short term research visit' a couple of years ago, and thus could not make the code neat.

Hope above thing helps.
Cheers!

**Comment by zhouxincheng** [comment]
> Hi @zhouxincheng , the file you mention was for a Similarity Task. The file had pairs of sentences for testing the performance of the model.
> 
> If you would want to try the model implementation, please skip that part by
> 
> * You can comment [line #73](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/siamese_lstm.py#L73) in the file [siamese_lstm.py](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/siamese_lstm.py) (Btw, I just changed that in a new commit).
> * You can comment lines #33, #45-50, #272-275 in the file [preprocess_data_lstm.py](https://github.com/vijaydwivedi75/Beyond_word2vec/blob/master/preprocess_data_lstm.py)
> 
> Apologies for the trouble during your implementation. This work was on a very 'short term research visit' a couple of years ago, and thus could not make the code neat.
> 
> Hope above thing helps.
> Cheers!
hi, @vijaydwivedi75 thank you for your explanation, it's helpful. Actually, after I posted the issue I understand the code totally.
