### ISSUE TITLE
The number of dataset is only 188000 not 376000 as the paper write

### ISSUE THREAD

**Issue by zhouxincheng** [vijaydwivedi75/Beyond_word2vec#3]
Hello, again! When I finish training, I found the test accuracy is only about 62%. So I check the data, I found the positive and negative data is only 188000 separately which is not consistent with that in your paper. Could you post it or just tell us how to extract it from the original dataset. Thanks.

**Comment by vijaydwivedi75** [comment]
Oh yes, I see that the `data_pair_pos` and `data_pair_neg` are not the final files that I have put on GitHub. Unfortunately, it is not on the PC with me right now. 

If you download and open (in terminal) the XL pack (or larger if you have enough resource) from [this link](http://paraphrase.org/#/download), it is in the format 

> LHS ||| PHRASE ||| PARAPHRASE ||| (FEATURE=VALUE )* ||| ALIGNMENT ||| ENTAILMENT

The pre-processing from the above format to `data_pair_pos` is a simple one (less than ~10 lines) and I have this snippet right now which did that. Please check the logic (its a very naive/rushed code, may not be fast)

```
import os
import re
import sys

ct = 0
val = []
os.system('wc -l ppdb')
with open('ppdb','r') as f:
	text = f.readlines()	
text = [i.split('|||') for i in text]
fp2 = open('out','w')			
for i in range(line):			
	fp2.write(str(text[0:line+1][i][1])+"--"+str(text[0:line+1][i][2])+'\n')
# uncomment the bottom part for similarity	
#    fp2.write(str(text[0:line+1][i][1])+"--"+str(text[0:line+1][i][2])+"--"+str(text[0:line+1][i][3][366:370])+'\n')
fp2.close()
f.close()
```

This pre-processing did not involve anything great, was just simple formatting.

And for the accuracy, you should get ~75% easily, try to train longer.

**Comment by zhouxincheng** [comment]
What's the "line" mean in the code? It's quite confusing.
Sorry to bother u

**Comment by vijaydwivedi75** [comment]
The `line` refers to the line (number of data line) in the original ppdb file downloaded from the website.

**Comment by zhouxincheng** [comment]
That doesn't make sense, because the text is already a list of all lines(btw, the text is much bigger the 37600 already)
What you do is extracting the "PHRASE" and "PARAPHRASE", right?

**Comment by vijaydwivedi75** [comment]
I am quoting this from the [PPDB site](http://paraphrase.org/#/download):

> File Format
> 
> PPDB is distributed as plain text files, with **one paraphrase rule per line**. For English, each line is formatted as follows:
> 
> LHS ||| PHRASE ||| PARAPHRASE ||| (FEATURE=VALUE )* ||| ALIGNMENT ||| ENTAILMENT
> Where SOURCE is an expression, TARGET is its paraphrase, LHS is the constituent or CCG-style slashed constituent label for the paraphrase pair. ENTAILMENT is an automatically assigned entailment relation (e.g. Equivalence for pairs like couch/sofa, or ForwardEntailment for pairs like dog/animal). See our ACL 2015 paper for a description of the entailment relations.
> 
> Each paraphrase pair is also associated with a list of FEATURES, such as estimated paraphrase and entailment probabilities. For a full description of the features see our ACL 2015 short paper

Look at the bold  **one paraphrase rule per line** above.

Each line from a PPDB file gets us a line in `data_pair_pos`.

**Comment by zhouxincheng** [comment]
I try to extract the "single unit vs multi-units" from the ppdb dataset, but I failed. I have tried many times, however, I just can't figure out how to extract data as that in **data_pair_pos**. Please help!
